name: Central Dispatcher

on:
  workflow_call:
    inputs:
      event_name:
        type: string
      ref:
        type: string
      head_ref:
        type: string
      comment_body:
        type: string

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Install gh CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Dispatch appropriate workflow
        env:
          GITHUB
