name: Central Dispatcher

on:
  workflow_call:
    inputs:
      event_name:
        type: string
      ref:
        type: string
      head_ref:
        type: string
      comment_body:
        type: string

jobs:
  on-merge-to-main:
    if: ${{ inputs.event_name == 'push' && inputs.ref == 'refs/heads/main' }}
    uses: ./on-merge-to-main.yml@main

  on-pull-request:
    if: ${{ inputs.event_name == 'pull_request' || (inputs.event_name == 'issue_comment' && inputs.comment_body == 'ci') }}
    uses: ./on-pull-request.yml@main
    with:
      pr_ref: ${{ inputs.head_ref }}

  on-release:
    if: ${{ inputs.event_name == 'release' }}
    uses: ./on-release.yml@main
