name: Central Workflow Dispatcher .NET 

on:
  workflow_call:
    inputs:
      dotnet:
        type: string
        required: false
      lint:
        type: boolean
        default: true
      codecov:
        type: boolean
        default: true
        
jobs:
  build-test:
    if: github.event_name != 'release'
    uses: MagmaWorks/Actions/.github/workflows/dotnet-build-test.yml@main
    with:
      lint: ${{ inputs.lint }}
      dotnet: ${{ inputs.dotnet }}
      
  codecov-upload:
    needs: build-test
    if: ${{ inputs.codecov == true && github.event_name != 'release' }}
    uses: MagmaWorks/Actions/.github/workflows/codecov-upload.yml@main
      
  pack:
    needs: build-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: MagmaWorks/Actions/.github/workflows/dotnet-pack-release.yml@main
    with:
      dotnet: ${{ inputs.dotnet }}
    permissions:
      actions: write
      contents: write
      checks: write

  push-nuget:
    if: github.event_name == 'release'
    uses: MagmaWorks/Actions/.github/workflows/release-push-nuget.yml@main
    secrets: inherit
    permissions:
      contents: write
      actions: write
