name: Codecov Upload

on:
  workflow_call:

jobs:
  Codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          directory: coverage
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
