name: Central Workflow Dispatcher .NET 

on:
  workflow_call:
    inputs:
      codecov:
        type: boolean
        default: true
      lint:
        type: boolean
        default: true
      dotnet:
        type: string
        required: false

jobs:
  build-test:
    uses: MagmaWorks/Actions/.github/workflows/dotnet-build-test.yml@main
    with:
      lint: ${{ inputs.lint }}
      dotnet: ${{ inputs.dotnet }}
    permissions:
      contents: write 
  
  codecov-upload:
    needs: build-test
    if: ${{ inputs.codecov == true }}
    uses: MagmaWorks/Actions/.github/workflows/codecov-upload.yml@main
    permissions:
      checks: write
      pull-requests: write
      
  release:
    needs: codecov-upload
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release' }}
    uses: MagmaWorks/Actions/.github/workflows/dotnet-publish.yml@main
    with:
      dotnet: ${{ inputs.dotnet }}
    permissions:
      actions: write
      contents: write
      pull-requests: write
      checks: write
      attestations: write     
