name: Publish Packages .NET

on:
  workflow_call:
    inputs:
      dotnet:
        type: string
        required: false

jobs:
  tag_new_version:
    uses: MagmaWorks/Actions/.github/workflows/tag-for-release.yml@main
    
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        if: "${{ inputs.dotnet != '' }}"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet }}

      - name: Pack
        run: dotnet pack --configuration Release --no-restore -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg /p:DebugType=portable /property:Configuration=Debug

      - name: Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./**/*.nupkg"
          tag: ${{ github.event.release.tag_name }}
          draft: false
          makeLatest: true
          allowUpdates: true
          removeArtifacts: true
          updateOnlyUnreleased: false

      - name: Push NuGet packages
        run: dotnet nuget push "./**/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

      - name: Delete old draft releases
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
