name: Lint, Build and Test .NET

on:
  workflow_call:
    inputs:
      lint:
        type: boolean
        default: true
      dotnet:
        type: string
        required: false
      test-filter:
        description: 'Filter expression for dotnet test (e.g., "Category!=Integration)")'
        type: string
        default: ''
      azure-artifacts-feed-url:
        description: 'URL for private Azure artifacts NuGet feed'
        type: string
        default: ''
      azure-artifacts-feed-user:
        description: 'User name for private Azure artifacts NuGet feed'
        type: string
        default: ''
      devexpress-artifacts-feed-url:
        description: 'URL for private DevExpress artifacts NuGet feed'
        type: string
        default: ''

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    outputs:
      coverage-artifact: coverage
      pack-artifact: package
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        if: ${{ inputs.dotnet != '' }}
        with:
          dotnet-version: ${{ inputs.dotnet }}

      - name: Run Lint
        if: github.event_name == 'pull_request' && inputs.lint == true
        id: lint-check
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: false
          dotnet_format: true
          check_name: "Lint using ${linter}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Package
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          dotnet pack --no-build \
            -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg \
            /p:DebugType=portable /property:Configuration=Debug

      - name: Test projects
        run: |
          dotnet test ${{ inputs.solution-path }} \
            --configuration Release \
            --no-build \
            --no-restore \
            --collect:"XPlat Code Coverage" \
            --logger trx \
            --results-directory coverage \
            --${{ inputs.test-filter && format('--filter "{0}"', inputs.test-filter) || '' }}

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload package artifact
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            ./**/*.nupkg
            ./**/*.snupkg
