name: Central Workflow Dispatcher .NET 

on:
  workflow_call:
    inputs:
      dotnet:
        type: string
        required: false
      lint:
        type: boolean
        default: true
      codecov:
        type: boolean
        default: true
    secrets:
      NUGET_API_KEY:
        required: false
        
jobs:
  build-test:
    if: github.event_name != 'release'
    uses: MagmaWorks/Actions/.github/workflows/dotnet-build-test.yml@main
    with:
      lint: ${{ inputs.lint }}
      dotnet: ${{ inputs.dotnet }}
    permissions:
      contents: write 
      checks: write
  
  codecov-upload:
    needs: build-test
    if: ${{ inputs.codecov == true }} && github.event_name != 'release'
    uses: MagmaWorks/Actions/.github/workflows/codecov-upload.yml@main
    permissions:
      checks: write
      pull-requests: write
      
  pack:
    needs: build-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: MagmaWorks/Actions/.github/workflows/dotnet-pack-release.yml@main
    with:
      dotnet: ${{ inputs.dotnet }}
    permissions:
      actions: write
      contents: write
      checks: write

  push-nuget:
    if: github.event_name == 'release'
    uses: MagmaWorks/Actions/.github/workflows/push-nuget.yml@main
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      actions: write
