name: On Pull Request -- Lint, Build, Test, Coverage

on:
  workflow_call:
    inputs:
      codecov:
        description: 'Upload code coverage to codecov.io'
        type: boolean
        default: true
        required: false

      lint:
        description: 'Lint (auto-fix errors and style)'
        type: boolean
        default: true
        required: false

      dotnet:
        description: 'Setup a specific dotnet version'
        type: string
        required: false
      
jobs:
  lint:
    if: inputs.lint == true
    name: Lint (auto-fix errors and style)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          fetch-depth: 0

      - name: Setup dotnet
        if: "${{ inputs.dotnet != '' }}"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet }}
      
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          dotnet_format: true

      - name: Push fixes back
        id: push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am "chore: auto-fix lint"
            git push
            echo "changes_pushed=true" >> $GITHUB_OUTPUT
          else
            echo "changes_pushed=false" >> $GITHUB_OUTPUT
          fi
  
  build-test:
    name: Build and test project
    needs: lint
    if: needs.lint.outputs.changes_pushed == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        if: "${{ inputs.dotnet != '' }}"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet }}

      - name: Build
        run: dotnet build --configuration Release
    
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage

      - name: Upload coverage reports to workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage

  codecov-upload:
    name: Upload coverage reports to codecov.io
    needs: build-test
    if: needs.lint.outputs.changes_pushed == 'false' && inputs.codecov == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Download coverage reports from workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: coverage

      - name: Upload coverage reports to codecov.io
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
