name: On Pull Request -- Lint, Build, Test, Coverage

on:
  workflow_call:
    inputs:
      upload-coverage:
        description: 'Upload code coverage to CodeCov.io'
        type: boolean
        default: true
        required: false
      
jobs:
  lint:
    name: Lint (auto-fix errors and style)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          dotnet_format: true
  
  build-test:
    name: Build, and test project
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: dotnet build
    
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage

  upload-coverage:
    name: Upload coverage reports to Codecov.io
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v5
        if: inputs.upload-coverage == true
        with:
          fail_ci_if_error: true
          directory: coverage
