name: On Pull Request -- Lint, Build, Test, Coverage

on:
  workflow_call:
      
jobs:
  lint:
    name: Lint (auto-fix errors and style)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          dotnet_format: true
  
  build-test:
    name: Build, test and report coverage
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: dotnet build
    
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
      
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: coverage
